# Use postgres/example user/password credentials
version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=adventure_development
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

